#!/bin/bash -xe

scons p=ios target=template_debug dev_build=yes library_type=shared_library debug_symbols=yes arch=arm64 verbose=yes visionos_simulator=yes opengl3=no vulkan=no IOS_TOOLCHAIN_PATH=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain $@
